/**
 * Adversarial payloads for the parser-boundary functions.
 *
 * Assembled from the inputs that actually defeated earlier versions of these
 * checks, plus the neighbouring tricks. It is deliberately shared: a payload
 * added because it fooled one boundary is then tested against all of them.
 *
 * Note the corpus contains payloads that MUST be accepted as well as ones that
 * must be refused — "//unpkg.com/x.js" resolves to a real CDN, so a rule that
 * rejects everything containing "//" is wrong, not safe. Tests over this corpus
 * assert invariants rather than a hand-written verdict per payload, so the table
 * cannot lock in whatever the implementation happens to do today.
 */

/** Candidate plugin `entry` values. */
export const ENTRY_PAYLOADS: readonly string[] = [
    "//evil.example/x.js",
    "//unpkg.com/x.js",
    "\\\\evil.example/x.js",
    "\\\\unpkg.com/x.js",
    "/\\evil.example/x.js",
    "/\\unpkg.com/x.js",
    "/\\/evil.example/x.js",
    "/\\/unpkg.com/x.js",
    "/\n/evil.example/x.js",
    "/\t/evil.example/x.js",
    "//evi\nl.example/x.js",
    "https://unpk\ng.com/x.js",
    "https://unpkg.com\t/x.js",
    "\u0000//evil.example/x.js",
    "\u0000//unpkg.com/x.js",
    "/plugins/x.mjs\u0000",
    "  https://unpkg.com/x.js  ",
    "\u007f//evil.example/x.js",
    "https://unpkg.com\u007f/x.js",
    "/plugins/x\u007f.mjs",
    "https:/unpkg.com/x.js",
    "https:unpkg.com/x.js",
    "https:/\\unpkg.com/x.js",
    "https:///unpkg.com/x.js",
    "HTTPS://unpkg.com/x.js",
    "http://unpkg.com/x.js",
    "javascript:alert(1)",
    "jav\tascript:alert(1)",
    "data:text/javascript,alert(1)",
    "https://unpkg.com@evil.example/x.js",
    "https://evil.example@unpkg.com/x.js",
    "https://unpkg.com%40evil.example/x.js",
    "https://GROND.DEV/x.js",
    "https://unpkg.com./x.js",
    "https://sub.grond.dev./x.js",
    "https://grond.dev../x.js",
    "https://unpkg.com.evil.example/x.js",
    "https://evilgrond.dev/x.js",
    "https://\uff55npkg.com/x.js",
    "https://unpkg\u3002com/x.js",
    "https://gr\u043end.dev/x.js",
    "https://xn--grnd-hoa.dev/x.js",
    "http://localhost:3000/api/camera/proxy/iframe?url=https://evil.example/x.js",
    "http://127.0.0.1:5173/src/main.mjs",
    "http://2130706433/plugins/x.mjs",
    "http://[::1]/plugins/x.mjs",
    "/plugins/../api/camera/proxy/iframe?url=https://evil.example/x.js",
    "/plugins/%2e%2e/api/camera/proxy/iframe?url=https://evil.example/x.js",
    "/plugins/..%2fapi/camera/proxy/iframe?url=https://evil.example/x.js",
    "/plugins/%252e%252e/api/camera/proxy/iframe?url=https://evil.example/x.js",
    "/api/camera/proxy/iframe?url=https://evil.example/x.js",
    "/..//evil.example/x.js",
    "/pluginsX/evil.mjs",
    "/plugins",
    "/plugins/../../plugins/ok.mjs",
    "/plugins//evil.example/x.js",
    "/plugins/aviation.mjs",
    "/e2e-fixtures/mock-plugin.js",
    "https://unpkg.com/pkg@1.0.0/dist/frontend.mjs",
    "https://cdn.jsdelivr.net/npm/pkg/dist/frontend.mjs",
];

/** Candidate post-login `callbackUrl` values. */
export const REDIRECT_PAYLOADS: readonly string[] = [
    "//evil.example/x",
    "////evil.example/x",
    "/\\evil.example/x",
    "\\\\evil.example/x",
    "/\\/evil.example/x",
    "/..//evil.example/x",
    "/../..//evil.example/x",
    "/ops/../..//evil.example/x",
    "..//evil.example/x",
    "/./..//evil.example/x",
    "/%2e%2e//evil.example/x",
    "/.%2e//evil.example/x",
    "https://evil.example/x",
    "https://app.example@evil.example/x",
    "//app.example@evil.example/x",
    "\t//evil.example/x",
    "\u0000//evil.example/x",
    "/\n/evil.example/x",
    "//evil.example/x\u007f",
    "javascript:alert(1)",
    "data:text/html,<script>alert(1)</script>",
    "/api/marketplace/install-redirect?manifest=https://evil.example/m.json",
    "/apiary/notes",
    "/ops/../api/marketplace/install-redirect",
    "/API/marketplace/install-redirect?manifest=https://evil.example/m.json",
    "/%61pi/marketplace/install-redirect",
    "https:/evil.example/x",
    "\u007f//evil.example/x",
    "/ops\u0000",
    "",
    "/ops",
    "/ops?a=1#b",
    "/admin/overview",
    "/",
    "/ops//detail",
    "/a/../ops",
    "https://app.example/ops?a=1",
    "/ops?next=//evil.example",
    "/ops#//evil.example",
    "/%2f%2fevil.example",
];
